qatzip_lz4: function declaration without a prototype for qzLZ4HeaderSz
On modern compilers it becomes a compilation error with message:

  error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]

Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@clyso.com>
(cherry picked from commit bdea75a9504d274850d807676902a8ea186d53f8)